### ISSUE TITLE
run dlhub sdk error 

### ISSUE THREAD

**Issue by Xundrug** [globus-labs/solvation-energy-ml#1]
when I run the dlhub-sdk, the error has occurred. Could you help me fix it?

```
python run_model.py CCCNCC
We have an exception : <parsl.app.errors.RemoteExceptionWrapper object at 0x1503520a8cf8>
Traceback (most recent call last):
  File "run_model.py", line 15, in <module>
    result = client.run(args.servable, args.smiles)
  File "/localhome/anaconda3/envs/solv_ml/lib/python3.6/site-packages/dlhub_sdk/client.py", line 276, in run
    return future.result(timeout=timeout) if not asynchronous else future
  File "/localhome/anaconda3/envs/solv_ml/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/localhome/anaconda3/envs/solv_ml/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/localhome/anaconda3/envs/solv_ml/lib/python3.6/site-packages/dlhub_sdk/utils/futures.py", line 55, in running
    results = self.client.get_result(self.task_id, verbose=True)
  File "/localhome/anaconda3/envs/solv_ml/lib/python3.6/site-packages/dlhub_sdk/client.py", line 308, in get_result
    result = self._fx_client.get_result(task_id)
  File "/localhome/anaconda3/envs/solv_ml/lib/python3.6/site-packages/funcx/sdk/client.py", line 335, in get_result
    task["exception"].reraise()
  File "/localhome/anaconda3/envs/solv_ml/lib/python3.6/site-packages/parsl/app/errors.py", line 131, in reraise
    reraise(t, v, tb)
  File "/localhome/anaconda3/envs/solv_ml/lib/python3.6/site-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/funcx_endpoint/executors/high_throughput/funcx_worker.py", line 142, in start
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/funcx_endpoint/executors/high_throughput/funcx_worker.py", line 205, in execute_task
  File "<string>", line 16, in dlhub_run
KeyError: 'data'
```

**Comment by WardLT** [comment]
Thanks for reaching out! We've traced the problem to a result of an update to DLHub's server, and are working to fix it.

**Comment by WardLT** [comment]
Sorry for the slowness, but we've got the DLHub backend fixed! Could you confirm this works @Xundrug ?
